version: '3.8'

services:
  db:
    image: mysql:8
    container_name: financial_crisis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financial_crisis
    ports:
      - "3306:3306"
